<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.0 setup script
 * Date: Tue, 05 Jul 2022 11:36:46 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Mysql cluster [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Mysql cluster';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = port_here;
$cfg['Servers'][$i]['socket'] = 'database_name_here';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'username_here';
$cfg['Servers'][$i]['password'] = 'password_here';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'I|Yn>"NC"%*HQxhX*]+#*"TJB`<+OYE~';
$cfg['FirstDayOfCalendar'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
